# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rc_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rc_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10rc_service.proto\"\x07\n\x05_None\")\n\x05Motor\x12\x11\n\tdirection\x18\x01 \x01(\r\x12\r\n\x05speed\x18\x02 \x01(\r\"\"\n\x0e\x44istanceSensor\x12\x10\n\x08\x64istance\x18\x01 \x01(\x01\"]\n\tGyroscope\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x03 \x03(\x01\x12\x11\n\tgyroscope\x18\x06 \x03(\x01\x12\x13\n\x0b\x61\x63\x63\x65l_range\x18\x07 \x03(\x01\x12\x12\n\ngyro_range\x18\x08 \x03(\x01\"\x16\n\x05Servo\x12\r\n\x05\x61ngle\x18\x01 \x01(\r\"\x1c\n\nAudioChunk\x12\x0e\n\x04\x64\x61ta\x18\xc4\xd8\x02 \x03(\r\"]\n\x07\x43ommand\x12\x12\n\x02mA\x18\x01 \x01(\x0b\x32\x06.Motor\x12\x12\n\x02mB\x18\x02 \x01(\x0b\x32\x06.Motor\x12\x14\n\x04\x65\x61r1\x18\x03 \x01(\x0b\x32\x06.Servo\x12\x14\n\x04\x65\x61r2\x18\x04 \x01(\x0b\x32\x06.Servo\"\xc0\x01\n\x07Message\x12\x1e\n\x05\x66ront\x18\x01 \x01(\x0b\x32\x0f.DistanceSensor\x12\x1e\n\x05\x66loor\x18\x02 \x01(\x0b\x32\x0f.DistanceSensor\x12\x1d\n\tgyroscope\x18\x03 \x01(\x0b\x32\n.Gyroscope\x12\x19\n\x04left\x18\x04 \x01(\x0b\x32\x0b.AudioChunk\x12\x1a\n\x05right\x18\x05 \x01(\x0b\x32\x0b.AudioChunk\x12\x0e\n\x06status\x18\x06 \x01(\x05\x12\x0f\n\x07message\x18\x07 \x01(\t2M\n\x07RCRobot\x12\x1f\n\x07Process\x12\x08.Command\x1a\x08.Message\"\x00\x12!\n\x0bSendCommand\x12\x08.Command\x1a\x06._None\"\x00\x62\x06proto3'
)




__NONE = _descriptor.Descriptor(
  name='_None',
  full_name='_None',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=27,
)


_MOTOR = _descriptor.Descriptor(
  name='Motor',
  full_name='Motor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='Motor.direction', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='Motor.speed', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=70,
)


_DISTANCESENSOR = _descriptor.Descriptor(
  name='DistanceSensor',
  full_name='DistanceSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='DistanceSensor.distance', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=106,
)


_GYROSCOPE = _descriptor.Descriptor(
  name='Gyroscope',
  full_name='Gyroscope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='Gyroscope.acceleration', index=0,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyroscope', full_name='Gyroscope.gyroscope', index=1,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accel_range', full_name='Gyroscope.accel_range', index=2,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyro_range', full_name='Gyroscope.gyro_range', index=3,
      number=8, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=201,
)


_SERVO = _descriptor.Descriptor(
  name='Servo',
  full_name='Servo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle', full_name='Servo.angle', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=225,
)


_AUDIOCHUNK = _descriptor.Descriptor(
  name='AudioChunk',
  full_name='AudioChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='AudioChunk.data', index=0,
      number=44100, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=255,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mA', full_name='Command.mA', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mB', full_name='Command.mB', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ear1', full_name='Command.ear1', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ear2', full_name='Command.ear2', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=350,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='front', full_name='Message.front', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='floor', full_name='Message.floor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gyroscope', full_name='Message.gyroscope', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left', full_name='Message.left', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right', full_name='Message.right', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='Message.status', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='Message.message', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=545,
)

_COMMAND.fields_by_name['mA'].message_type = _MOTOR
_COMMAND.fields_by_name['mB'].message_type = _MOTOR
_COMMAND.fields_by_name['ear1'].message_type = _SERVO
_COMMAND.fields_by_name['ear2'].message_type = _SERVO
_MESSAGE.fields_by_name['front'].message_type = _DISTANCESENSOR
_MESSAGE.fields_by_name['floor'].message_type = _DISTANCESENSOR
_MESSAGE.fields_by_name['gyroscope'].message_type = _GYROSCOPE
_MESSAGE.fields_by_name['left'].message_type = _AUDIOCHUNK
_MESSAGE.fields_by_name['right'].message_type = _AUDIOCHUNK
DESCRIPTOR.message_types_by_name['_None'] = __NONE
DESCRIPTOR.message_types_by_name['Motor'] = _MOTOR
DESCRIPTOR.message_types_by_name['DistanceSensor'] = _DISTANCESENSOR
DESCRIPTOR.message_types_by_name['Gyroscope'] = _GYROSCOPE
DESCRIPTOR.message_types_by_name['Servo'] = _SERVO
DESCRIPTOR.message_types_by_name['AudioChunk'] = _AUDIOCHUNK
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_None = _reflection.GeneratedProtocolMessageType('_None', (_message.Message,), {
  'DESCRIPTOR' : __NONE,
  '__module__' : 'rc_service_pb2'
  # @@protoc_insertion_point(class_scope:_None)
  })
_sym_db.RegisterMessage(_None)

Motor = _reflection.GeneratedProtocolMessageType('Motor', (_message.Message,), {
  'DESCRIPTOR' : _MOTOR,
  '__module__' : 'rc_service_pb2'
  # @@protoc_insertion_point(class_scope:Motor)
  })
_sym_db.RegisterMessage(Motor)

DistanceSensor = _reflection.GeneratedProtocolMessageType('DistanceSensor', (_message.Message,), {
  'DESCRIPTOR' : _DISTANCESENSOR,
  '__module__' : 'rc_service_pb2'
  # @@protoc_insertion_point(class_scope:DistanceSensor)
  })
_sym_db.RegisterMessage(DistanceSensor)

Gyroscope = _reflection.GeneratedProtocolMessageType('Gyroscope', (_message.Message,), {
  'DESCRIPTOR' : _GYROSCOPE,
  '__module__' : 'rc_service_pb2'
  # @@protoc_insertion_point(class_scope:Gyroscope)
  })
_sym_db.RegisterMessage(Gyroscope)

Servo = _reflection.GeneratedProtocolMessageType('Servo', (_message.Message,), {
  'DESCRIPTOR' : _SERVO,
  '__module__' : 'rc_service_pb2'
  # @@protoc_insertion_point(class_scope:Servo)
  })
_sym_db.RegisterMessage(Servo)

AudioChunk = _reflection.GeneratedProtocolMessageType('AudioChunk', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOCHUNK,
  '__module__' : 'rc_service_pb2'
  # @@protoc_insertion_point(class_scope:AudioChunk)
  })
_sym_db.RegisterMessage(AudioChunk)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'rc_service_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'rc_service_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)



_RCROBOT = _descriptor.ServiceDescriptor(
  name='RCRobot',
  full_name='RCRobot',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=547,
  serialized_end=624,
  methods=[
  _descriptor.MethodDescriptor(
    name='Process',
    full_name='RCRobot.Process',
    index=0,
    containing_service=None,
    input_type=_COMMAND,
    output_type=_MESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendCommand',
    full_name='RCRobot.SendCommand',
    index=1,
    containing_service=None,
    input_type=_COMMAND,
    output_type=__NONE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RCROBOT)

DESCRIPTOR.services_by_name['RCRobot'] = _RCROBOT

# @@protoc_insertion_point(module_scope)
